# -*- coding: utf-8 -*-
"""Python error types checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lsL-OM_7rDaTaVTc6VXDn-x7cMkVCGG

# Rectify the code in each cell and **explain the error in comments**

### index error
"""

mylist=[14, "hello", 967]
mylist[2]

import pandas 
import numpy

"""# syntax error"""

print("python errors")

"""# key error"""

mydictionnary={True:"hello",False:"bye", '3':"python"}
mydictionnary[True]

"""# indentation error"""

i=14
while i<78:
 print(i)
i+=1

"""# StopIteration"""

it=iter([1,2,3])
next(it)

"""# TypeError

"""

'15'+'15'

"""# ValueError"""

python = int

"""# NameError"""

python = str

"""# ZeroDivisionError"""

x=19/1